--SET IDENTITY_INSERT dbo.Books OFF;

INSERT INTO Books(barcode, title, author, genre) 
VALUES
(299946, 'A Tale of Two Cities', 'Charles Dickens', 'Historical fiction')
,(299947, 'The Little Prince Le Petit Prince)', 'Antoine de Saint-Exupéry', 'Fantasy children fiction')
,(299948, 'The Alchemist O Alquimista)', 'Paulo Coelho', 'Fantasy')
,(299949, 'Harry Potter and the Philosopher Stone', 'J. K. Rowling', 'Fantasy children fiction')
,(299950, 'And Then There Were None', 'Agatha Christie', 'Mystery')
,(299951, 'Dream of the Red Chamber', 'Cao Xueqin', 'Family saga')
,(299952, 'The Hobbit', 'J. R. R. Tolkien', 'Fantasy children fiction')
,(299953, 'She: A History of Adventure', 'H. Rider Haggard', 'Adventure')
,(299954, 'The Da Vinci Code', 'Dan Brown', 'Mystery thriller')
,(299955, 'Harry Potter and the Chamber of Secrets', 'J. K. Rowling', 'Fantasy')
,(299956, 'Harry Potter and the Prisoner of Azkaban', 'J. K. Rowling', 'Fantasy')
,(299957, 'Harry Potter and the Goblet of Fire', 'J. K. Rowling', 'Fantasy')
,(299958, 'Harry Potter and the Order of the Phoenix', 'J. K. Rowling', 'Fantasy')
,(299959, 'Harry Potter and the Half-Blood Prince', 'J. K. Rowling', 'Fantasy')
,(299960, 'Harry Potter and the Deathly Hallows', 'J. K. Rowling', 'Fantasy')
,(299961, 'The Catcher in the Rye', 'J. D. Salinger', 'Coming-of-age')
,(299962, 'The Bridges of Madison County', 'Robert James Waller', 'Romance')
,(299963, 'One Hundred Years of Solitude Cien años de soledad)', 'Gabriel García Márquez', 'Magic realism')
,(299964, 'Lolita', 'Vladimir Nabokov', 'Novel')
,(299965, 'Heidi', 'Johanna Spyri', 'Children fiction')
,(299966, 'The Common Sense Book of Baby and Child Care', 'Benjamin Spock', 'Manual')
,(299967, 'Anne of Green Gables', 'Lucy Maud Montgomery', 'Children novel')
,(299968, 'Black Beauty', 'Anna Sewell', 'Children literature')
,(299969, 'The Name of the Rose Il Nome della Rosa)', 'Umberto Eco', 'Historical novel mystery')
,(299970, 'The Eagle Has Landed', 'Jack Higgins', 'War thriller')
,(299971, 'Watership Down', 'Richard Adams', 'Fantasy')
,(299972, 'The Hite Report', 'Shere Hite', 'Sexology')
,(299973, 'Charlotte Web', 'E. B. White; illustrated by Garth Williams', 'Children fiction')
,(299974, 'The Ginger Man', 'J. P. Donleavy', 'Novel')
,(299975, 'The Tale of Peter Rabbit', 'Beatrix Potter', 'Children Literature')
,(299976, 'Jonathan Livingston Seagull', 'Richard Bach', 'Novella Self-help')
,(299977, 'The Very Hungry Caterpillar', 'Eric Carle', 'Children Literature picture book')
,(299978, 'A Message to Garcia', 'Elbert Hubbard', 'Essay/Literature')
,(299979, 'To Kill a Mockingbird', 'Harper Lee', 'Southern Gothic')
,(299980, 'Flowers in the Attic', 'V. C. Andrews', 'Gothic horror Family saga')
,(299981, 'Cosmos', 'Carl Sagan', 'Popular science Anthropology AstrophysicsCosmology Philosophy History')
,(299982, 'Sophie World', 'Jostein Gaarder', 'Philosophical novel Young adult')
,(299983, 'Angels & Demons', 'Dan Brown', 'Mystery-thriller')
,(299984, 'Alcoholics Anonymous', 'William Griffith Wilson', 'Self-Help')
,(299985, 'Kane and Abel', 'Jeffrey Archer', 'Novel')
,(299986, 'How the Steel Was Tempered', 'Nikolai Ostrovsky', 'Socialist realist novel')
,(299987, 'War and Peace', 'Leo Tolstoy', 'Historical novel')
,(299988, 'The Adventures of Pinocchio Le avventure di Pinocchio)', 'Carlo Collodi', 'Fantasy Children fiction')
,(299989, 'The Diary of Anne Frank Het Achterhuis)', 'Anne Frank', 'Historical non-fiction Autobiography Memoir Bildungsroman / Coming of AgeJewish literature')
,(299990, 'Your Erroneous Zones', 'Wayne Dyer', 'Self-help')
,(299991, 'The Thorn Birds', 'Colleen McCullough', 'Romantic family saga')
,(299992, 'The Kite Runner', 'Khaled Hosseini', ' Historical fiction')
,(299993, 'Valley of the Dolls', 'Jacqueline Susann', 'Novel')
,(299994, 'How to Win Friends and Influence People', 'Dale Carnegie', 'Self-help')
,(299995, 'The Great Gatsby', 'F. Scott Fitzgerald', 'Novel tragedy')
,(299996, 'Gone with the Wind', 'Margaret Mitchell', 'Historical fiction')
,(299997, 'Rebecca', 'Daphne du Maurier', 'Gothic novel')
,(299998, 'The Revolt of Mamie Stover', 'William Bradford Huie', 'Fiction')
,(299999, 'The Girl with the Dragon Tattoo', 'Stieg Larsson', 'Fiction')
,(300000, 'The Lost Symbol', 'Dan Brown', 'Fiction')
,(300001, 'The Hunger Games', 'Suzanne Collins', 'Young adult fiction')
,(300002, 'James and the Giant Peach', 'Roald Dahl', 'Children novel')
,(300003, 'The Young Guard', 'Alexander Alexandrovich Fadeyev', 'Young adult historical novel')
,(300004, 'Who Moved My Cheese?', 'Spencer Johnson', 'Self-help motivational business fablepsychology leadership parable')
,(300005, 'A Brief History of Time', 'Stephen Hawking', 'Popular science')
,(300006, 'Paul et Virginie', 'Jacques-Henri Bernardin de Saint-Pierre', 'Novel')
,(300007, 'Lust for Life', 'Irving Stone', 'Biographical novel')
,(300008, 'The Wind in the Willows', 'Kenneth Grahame', 'Children literature')
,(300009, 'The 7 Habits of Highly Effective People', 'Stephen R. Covey', 'Self-help')
,(300010, 'Virgin Soil Upturned ', 'Mikhail Sholokhov', 'Novel')
,(300011, 'The Celestine Prophecy', 'James Redfield', 'New-age spiritual novel')
,(300012, 'The Fault in Our Stars', 'John Green', 'Young adult romantic novel')
,(300013, 'The Girl on the Train', 'Paula Hawkins', 'Thriller')
,(300014, 'The Shack', 'William P. Young', 'Novel')
,(300015, 'Uncle Styopa', 'Sergey Mikhalkov', 'Children Literature picture book')
,(300016, 'The Godfather', 'Mario Puzo', 'Crime novel')
,(300017, 'Love Story', 'Erich Segal', 'Romance novel')
,(300018, 'Catching Fire', 'Suzanne Collins', 'Young Adult novel adventuredystopian science fiction')
,(300019, 'Mockingjay', 'Suzanne Collins', 'Young Adult novel adventure war science fiction action thriller')
,(300020, 'Andromeda Nebula', 'Ivan Yefremov', 'Science fiction novel')
,(300021, 'Gone Girl', 'Gillian Flynn', 'Crime thriller novel')
,(300022, 'Things Fall Apart', 'Chinua Achebe', 'Novel')
,(300023, 'The Happy Hooker: My Own Story', 'Xaviera Hollander', 'Memoir')
,(300024, 'Jaws', 'Peter Benchley', 'Thriller')
,(300025, 'Love You Forever', 'Robert Munsch', 'Children literature picture book fiction')
,(300026, 'The Women Room', 'Marilyn French', 'Feminist novel')
,(300027, 'What to Expect When You re Expecting', 'Arlene Eisenberg and Heidi Murkoff', 'Pregnancy guide')
,(300028, 'Adventures of Huckleberry Finn', 'Mark Twain', 'Picaresque novel satireRobinsonade')
,(300029, 'The Secret Diary of Adrian Mole', 'Sue Townsend', 'Young adult novel')
,(300030, 'Pride and Prejudice', 'Jane Austen', 'Classic regency novel romance')
,(300031, 'Kon-Tiki: Across the Pacific in a Raft ', 'Thor Heyerdahl', 'Travel literature')
,(300032, 'The Good Soldier Svejk', 'Jaroslav Hašek', 'Unfinished satirical dark comedy novel')
,(300033, 'Where the Wild Things Are', 'Maurice Sendak', 'Children picture book')
,(300034, 'The Power of Positive Thinking', 'Norman Vincent Peale', 'Self-help')
,(300035, 'The Secret', 'Rhonda Byrne', 'Self-help')
,(300036, 'Fear of Flying', 'Erica Jong', 'Romantic novel')
,(300037, 'Dune', 'Frank Herbert', 'Science fiction novel')
,(300038, 'Charlie and the Chocolate Factory', 'Roald Dahl', 'Children fantasy novel')
,(300039, 'The Naked Ape', 'Desmond Morris', 'Social Science Anthropology Psychology')
,(300040, 'Where the Crawdads Sing', 'Delia Owens', 'Coming-of-age murder mystery')
,(300041, 'Follow Your Heart', 'Susanna Tamaro', 'Sentimentalepistolary novel')
,(300042, 'Matilda', 'Roald Dahl', 'Children literature')
,(300043, 'The Book Thief', 'Markus Zusak', 'Young adult fiction')
,(300044, 'The Horse Whisperer', 'Nicholas Evans', '')
,(300045, 'Goodnight Moon', 'Margaret Wise Brown', 'Children literature')
,(300046, 'The Neverending Story', 'Michael Ende', 'Children literature')
,(300047, 'All the Light We Cannot See', 'Anthony Doerr', 'Historical fiction war novel')
,(300048, 'Fifty Shades of Grey', 'E. L. James', 'Erotica')
,(300049, 'The Outsiders', 'S. E. Hinton', '')
,(300050, 'Guess How Much I Love You', 'Sam McBratney', '')
,(300051, 'Shogun', 'James Clavell', '')
,(300052, 'The Poky Little Puppy', 'Janette Sebring Lowrey', '')
,(300053, 'The Pillars of the Earth', 'Ken Follett', 'Historical fiction')
,(300054, 'Perfume Das Parfum)', 'Patrick Süskind', '')
,(300055, 'The Grapes of Wrath', 'John Steinbeck', '')
,(300056, 'The Shadow of the Wind La sombra del viento)', 'Carlos Ruiz Zafón', '')
,(300057, 'Interpreter of Maladies', 'Jhumpa Lahiri', '')
,(300058, 'Becoming', 'Michelle Obama', '')
,(300059, 'The Hitchhiker Guide to the Galaxy', 'Douglas Adams', 'Science fiction')
,(300060, 'Tuesdays with Morrie', 'Mitch Albom', '')
,(300061, 'God Little Acre', 'Erskine Caldwell', '')
,(300062, 'A Wrinkle in Time', 'Madeleine L Engle', '')
,(300063, 'Long Walk to Freedom', 'Nelson Mandela', '')
,(300064, 'The Old Man and the Sea', 'Ernest Hemingway', '')
,(300065, 'Life After Life', 'Raymond Moody', '')
,(300066, 'Momo', 'Michael Ende', 'Children literature')
,(300067, 'Peyton Place', 'Grace Metalious', '')
,(300068, 'The Giver', 'Lois Lowry', 'Dystopian fiction')
,(300069, 'Me Before You', 'Jojo Moyes', '')
,(300070, 'Man Search for Meaning Ein Psychologe erlebt das Konzentrationslager)', 'Viktor Frankl', '')
,(300071, 'The Divine Comedy La Divina Commedia)', 'Dante Alighieri', '')
,(300072, 'The Prophet', 'Kahlil Gibran', '')
,(300073, 'The Boy in the Striped Pyjamas', 'John Boyne', '')
,(300074, 'The Exorcist', 'William Peter Blatty', 'Horror')
,(300075, 'The Gruffalo', 'Julia Donaldson', '')
,(300076, 'Fifty Shades Darker', 'E. L. James', '')
,(300077, 'Tobacco Road', 'Erskine Caldwell', '')
,(300078, 'Ronia the Robber Daughter', 'Astrid Lindgren', '')
,(300079, 'The Cat in the Hat', 'Dr. Seuss', '')
,(300080, 'Diana: Her True Story', 'Andrew Morton', '')
,(300081, 'The Help', 'Kathryn Stockett', '')
,(300082, 'Catch-22', 'Joseph Heller', '')
,(300083, 'The Stranger', 'Albert Camus', '')
,(300084, 'Eye of the Needle', 'Ken Follett', '')
,(300085, 'The Lovely Bones', 'Alice Sebold', '')
,(300086, 'Wild Swans', 'Jung Chang', '')
,(300087, 'Santa Evita', 'Tomás Eloy Martínez', '')
,(300088, 'Night ', 'Elie Wiesel', '')
,(300089, 'Confucius from the Heart ', 'Yu Dan', '')
,(300090, 'The Total Woman', 'Marabel Morgan', '')
,(300091, 'Knowledge-value Revolution', 'Taichi Sakaiya', '')
,(300092, 'Problems in China Socialist Economy', 'Xue Muqiao', '')
,(300093, 'What Color Is Your Parachute?', 'Richard Nelson Bolles', '')
,(300094, 'The Dukan Diet', 'Pierre Dukan', '')
,(300095, 'The Joy of Sex', 'Alex Comfort', '')
,(300096, 'The Gospel According to Peanuts', 'Robert L. Short', '')
,(300097, 'The Subtle Art of Not Giving a Fuck', 'Mark Manson', '')
,(300098, 'Life of Pi', 'Yann Martel', '')
,(300099, 'The Front Runner', 'Patricia Nell Warren', '')
,(300100, 'The Goal', 'Eliyahu M. Goldratt', '')
,(300101, 'Fahrenheit 451', 'Ray Bradbury', '')
,(300102, 'Angela Ashes', 'Frank McCourt', '')
,(300103, 'The Story of My Experiments with Truth ', 'Mohandas Karamchand Gandhi', '')
,(300104, 'Bridget Jones Diary', 'Helen Fielding', '')
,(300105, 'American Girl', 'Various authors', 'young adult')
,(300106, 'Berenstain Bears', 'Stan and Jan Berenstain', 'young adult')
,(300107, 'Chicken Soup for the Soul', 'Jack Canfield Mark Victor Hansen', 'young adult')
,(300108, 'Choose Your Own Adventure', 'Various authors', 'young adult')
,(300109, 'Clifford the Big Red Dog', 'Norman Bridwell', 'young adult')
,(300110, 'Diary of a Wimpy Kid', 'Jeff Kinney', 'young adult')
,(300111, 'Dirk Pitt', 'Clive Cussler', 'young adult')
,(300112, 'Fifty Shades', 'E. L. James', 'young adult')
,(300113, 'Frank Merriwell', 'Gilbert Patten', 'young adult')
,(300114, 'Geronimo Stilton', 'Elisabetta Dami', 'young adult')
,(300115, 'Goosebumps', 'R. L. Stine', 'young adult')
,(300116, 'Harry Potter', 'J. K. Rowling', 'young adult')
,(300117, 'James Bond', 'Ian Fleming', 'young adult')
,(300118, 'Little Critter', 'Mercer Mayer', 'young adult')
,(300119, 'Martine', 'Gilbert Delahaye Marcel Marlier', 'young adult')
,(300120, 'Millennium', 'Stieg Larsson David Lagercrantz', 'young adult')
,(300121, 'Mr. Men', 'Roger Hargreaves Adam Hargreaves', 'young adult')
,(300122, 'Nancy Drew', 'Various authors as Carolyn Keene', 'young adult')
,(300123, 'Noddy', 'Enid Blyton', 'young adult')
,(300124, 'Percy Jackson & the Olympians', 'Rick Riordan', 'young adult')
,(300125, 'Perry Mason', 'Erle Stanley Gardner', 'young adult')
,(300126, 'Peter Rabbit', 'Beatrix Potter', 'young adult')
,(300127, 'Robert Langdon', 'Dan Brown', 'young adult')
,(300128, 'San-Antonio', 'Frédéric Dard', 'young adult')
,(300129, 'SAS', 'Gérard de Villiers', 'young adult')
,(300130, 'Star Wars', 'Various authors', 'young adult')
,(300131, 'Sweet Valley High', 'Francine Pascal and ghostwriters', 'young adult')
,(300132, 'The Baby-sitters Club', 'Ann Martin', 'young adult')
,(300133, 'The Chronicles of Narnia', 'C. S. Lewis', 'young adult')
,(300134, 'The Hunger Games', 'Suzanne Collins', 'young adult')
,(300135, 'The Railway Series', 'Rev. W. Awdry Christopher Awdry', 'young adult')
,(300136, 'Twilight', 'Stephenie Meyer', 'young adult')
